name: Build WebUI
on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  Windows-WebUI:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - name: Windows-WebUI
        shell: cmd
        run: |
          mingw32-make -j8

  Linux-WebUI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linux-WebUI
        run: |
          sudo ln -s llvm-ar-13 /usr/bin/llvm-ar
          sudo ln -s llvm-ranlib-13 /usr/bin/llvm-ranlib
          make -j8

  macOS-WebUI:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: macOS-WebUI
        run: |
          make -j8
