name: Build WebUI  
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  GCC-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linux-GCC-Build
        run: |
          cd build/Linux/GCC
          make

  MinGW-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Windows-MinGW-Build
        shell: cmd
        run: |
          cd build/Windows/GCC
          mingw32-make

  MSVC-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - name: Windows-MSVC-Build
        shell: cmd
        run: |
          cd build/Windows/MSVC
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake
