name: Build WebUI  
on:
  push:
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  GCC-Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}/examples/Linux/GCC/
        run: make static

  MinGW-Windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/@v2

      - name: Build
        working-directory: ${{github.workspace}}/examples/Windows/GCC/
        shell: cmd
        run: mingw32-make static

  MSVC-Windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}/examples/Windows/MSVC/
        shell: cmd
        run: |
             call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
             nmake static
