name: Lint

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: '.'
          exclude: './src/civetweb/*'
          clangFormatVersion: 16
