# http://webui.me
# https://github.com/webui-dev/webui
# Copyright (c) 2020-2023 Hassan Draga.
# Licensed under MIT License.
# All rights reserved.
#
# Special Thanks to Turiiya (https://github.com/ttytm)

name: Linux
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle WebUI Bridge
        run: |
          npm i -g esbuild
          chmod +x bridge/build.sh
          bridge/build.sh
      - uses: actions/cache@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge

  build:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [GCC, Clang]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge
          fail-on-cache-miss: true
      - name: Link Libraries
        if: matrix.compiler == 'clang'
        run: |
          sudo ln -s llvm-ar-13 /usr/bin/llvm-ar
          sudo ln -s llvm-ranlib-13 /usr/bin/llvm-ranlib
      - name: Build Debug Target
        run: |
          compiler=${{ matrix.compiler }}
          make COMPILER=${compiler,,} debug
      - name: Build Release Target
        run: |
          compiler=${{ matrix.compiler }}
          make COMPILER=${compiler,,}
      - name: Prepare Artifact
        run: |
          cp -r include dist
          artifact=webui-${{ runner.os }}-${{ matrix.compiler }}-x64
          # Convert to lowercase (`,,` ^= lowercase shell param)
          artifact=${artifact,,}
          # Add the ARTIFACT name as GitHub environment variable.
          echo "ARTIFACT=$artifact" >> $GITHUB_ENV
          mv dist/ $artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Prepare Release Archive
        if: github.ref_type == 'tag'
        run: tar -czvf $artifact.tar.gz ${{ env.ARTIFACT }}
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT }}.tar.gz
