# http://webui.me
# https://github.com/webui-dev/webui
# Copyright (c) 2020-2023 Hassan Draga.
# Licensed under MIT License.
# All rights reserved.
#
# Special Thanks to Turiiya (https://github.com/ttytm)

name: macOS
on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bundle WebUI Bridge
        run: |
          npm i -g esbuild
          chmod +x bridge/build.sh
          bridge/build.sh
      - uses: actions/cache@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge

  build:
    needs: setup
    runs-on: macos-latest
    permissions:
      contents: write
    strategy:
      matrix:
        compiler: [Clang]
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: bridge/webui_bridge.h
          key: ${{ runner.os }}-${{ github.sha }}-bridge
          fail-on-cache-miss: true
      - name: Build Debug Target
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            make ARCH_TARGET="-target arm64-apple-darwin" debug
          else
            make debug
          fi
      - name: Build Release Target
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            make ARCH_TARGET="-target arm64-apple-darwin"
          else
            make
          fi
      - name: Prepare Artifacts
        run: |
          cp -r include dist
          # Add the ARTIFACT name(lowercased) as GitHub environment variable.
          artifact=webui-$(echo ${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.arch }} | tr '[:upper:]' '[:lower:]')
          echo "ARTIFACT=$artifact" >> $GITHUB_ENV
          mv dist/ $artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}
      - name: Prepare Release Archive
        if: github.ref_type == 'tag'
        run: tar -czvf $artifact.tar.gz ${{ env.ARTIFACT }}
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT }}.tar.gz
